[package]
name = "greedy-shopper"
version = "0.1.0"
authors = ["James Taylor <jamestaylor3@protonmail.com>"]
edition = "2018"

[lib]
name = "shopper"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.10.1"
features = ["extension-module"]

[dependencies]
itertools = "0.9.0"